version: '3'

services:
  web:
    restart: always
    build: 
      context: ./
      dockerfile: ./compose/Dockerfile
    ports:
     - "8000:8000"
    volumes:
      - .:/code
    env_file: env/.env
    command: /start.sh
    depends_on:
      - postgres
      - redis
      
  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file: env/.postgres

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  web-django:
  web-static:
  pgdata:
  redisdata:
