# Generated by Django 4.1.2 on 2022-10-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_playlist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(0, 'Pop'), (1, 'Country'), (2, 'Rhythm & Blues'), (3, 'Hip Hop'), (4, 'Gospel'), (5, 'K-Pop'), (6, "Rock 'N Roll"), (7, 'Techno/Dance'), (8, 'Flamenco'), (9, 'Classical')], max_length=150)),
            ],
        ),
    ]
