# Generated by Django 4.1.2 on 2022-10-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('pop', 'Pop'), ('country', 'Country'), ('rnb', 'Rhythm & Blues'), ('hip_hop', 'Hip Hop'), ('gospel', 'Gospel'), ('kpop', 'K-Pop'), ('rock', "Rock 'N Roll"), ('techno', 'Techno/Dance'), ('flamenco', 'Flamenco'), ('classical', 'Classical')], max_length=150),
        ),
    ]
