# Generated by Django 4.1.2 on 2022-10-06 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_color', models.CharField(blank=True, max_length=55, null=True)),
                ('favorite_band', models.CharField(blank=True, max_length=55, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Support',
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.profile'),
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
