FROM python:3.9-buster
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code

RUN apt-get update && apt-get install build-essential -y
COPY requirements.txt /code/
RUN pip install --upgrade pip && \
pip install -r requirements.txt
COPY . /code/

COPY ./compose/start.sh /start.sh
RUN chmod +x /start.sh

COPY ./compose/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]
